name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Use a Node.js version compatible with your project

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install
    
    - name: Install dependencies for WebKit
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff1 \
          libvpx7 \
          libevent-2.1-7 \
          libopus0 \
          libgstallocators-1.0-0 \
          libgstapp-1.0-0 \
          libgstpbutils-1.0-0 \
          libgstaudio-1.0-0 \
          libgstgl-1.0-0 \
          libgsttag-1.0-0 \
          libgstvideo-1.0-0 \
          libgstcodecparsers-1.0-0 \
          libgstfft-1.0-0 \
          libflite1 \
          libharfbuzz-icu0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libgles2-mesa \
          libx264-160

    - name: Start server in the background
      run: npm start &
    
    - name: Wait for server to be ready
      run: npx wait-on http://localhost:5000

    - name: Run Playwright tests in all browsers
      run: npx playwright test --project=Chromium --project=Chrome --project=Firefox --project=WebKit
  