name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Use a Node.js version compatible with your project

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm run test

    - name: Run Cypress tests
      run: npm run test:cypress
      env:
        # Set DISPLAY environment variable for Cypress in headless mode
        DISPLAY: ":99.0"